conscious_consumer/accounts/urls.py
from django.urls import path
import django.contrib.auth.views as auth_views
from accounts.views import (
    SignupView,
    ProfileDetail,
    ProfileUpdate,
    UserUpdate,
    UserDelete,
    BeginPasswordChange,
    PasswordChangeComplete,
)

app_name = "accounts"
urlpatterns = [
    # auth related views
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="accounts/auth/login.html"),
        name="login",
    ),
    path("signup/", SignupView.as_view(), name="signup"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    # profile related views
    path(
        "<int:pk>/change-profile-image/", ProfileUpdate.as_view(), name="change_image"
    ),
    path(
        "<int:pk>/change-account-info/",
        UserUpdate.as_view(),
        name="change_account_info",
    ),
    path("<int:pk>/delete-account/", UserDelete.as_view(), name="profile_delete"),
    path("<int:pk>/", ProfileDetail.as_view(), name="profile_detail"),
    # password-related views=
    path("password-change/", BeginPasswordChange.as_view(), name="password_change"),
    path(
        "password-change/done/",
        PasswordChangeComplete.as_view(),
        name="password_change_done",
    ),
]

conscious_consumer/api/urls.py
from django.urls import path
from .views import GoalData

app_name = "api"
urlpatterns = [
    # Returns achievement and fail data for a Goal
    path("<int:pk>/chart/data/", GoalData.as_view(), name="goal_data"),
]

conscious_consumer/budget/urls.py
from django.urls import path
from .views import (
    AllGoalList,
    PersonalGoalList,
    PersonalGoalDetail,
    PublicGoalDetail,
    GoalCreate,
    GoalUpdate,
    GoalDelete,
)

app_name = "budget"
urlpatterns = [
    # Goal-related CRUD URLs - id of user is passed to query string on personal
    path("goals/public/", AllGoalList.as_view(), name="goal_list_public"),
    path("goals/create/", GoalCreate.as_view(), name="goal_create"),
    path("goals/update/<slug:slug>/", GoalUpdate.as_view(), name="goal_update"),
    path("goal/delete/<slug:slug>/", GoalDelete.as_view(), name="goal_delete"),
    path("goals/<slug:slug>/", PublicGoalDetail.as_view(), name="goal_detail_public"),
    path(
        "goals/<int:pk>/<slug:slug>/",
        PersonalGoalDetail.as_view(),
        name="goal_detail_personal",
    ),
    path("<int:pk>/", PersonalGoalList.as_view(), name="goal_list_personal"),
]

conscious_consumer/store/urls.py
from django.urls import path
from .views import (
    ProductList,
    ProductCreate,
    ProductDetail,
    ProductUpdate,
    ProductDelete,
)

app_name = "store"
urlpatterns = [
    # Product CRUD-related URLs
    path("products/", ProductList.as_view(), name="product_list"),
    path("products/new/", ProductCreate.as_view(), name="product_create"),
    path("products/<slug:slug>/edit/", ProductUpdate.as_view(), name="product_update"),
    path(
        "products/<slug:slug>/delete/", ProductDelete.as_view(), name="product_delete"
    ),
    path("products/<slug:slug>/", ProductDetail.as_view(), name="product_detail"),
]

conscious_consumer/templates/partials/footer.html
<!-- conscious_consumer/templates/partials/footer.html -->
<hr class="mt-0">
<footer id="footer">
    <div>
        <p class="ml-3">&copy; 2020 Conscious Consumer Inc.</p>
    </div>
    <div class="row">
        <p class="ml-5">  Logo icon made by <a href="https://www.flaticon.com/authors/freepik" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a>
    </div>
    <div class="row">
        <p class="ml-5">
            <a href="https://icons8.com/icons/set/user">
                User profile icon</a> made by
            <a href="https://icons8.com">
                Icons8
            </a>.
        </p>
    </div>
    <div class="row">
        <p class="ml-5">Products found through
            <a href="https://github.com/philsturgeon/awesome-earth#footprint-calculators">
                Phil Sturgeon's Awesome Earth
            </a>open-source project on GitHub.
        </p>
    </div>
</footer>

conscious_consumer/templates/partials/form.html
<!-- conscious_consumer/templates/partials/form.html -->
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="btn btn-success" type="submit" value="Confirm">
</form>

conscious_consumer/templates/partials/meta.html
<!-- conscious_consumer/templates/partials/meta.html -->
{% load static %}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<title>Conscious Consumer</title>
<!-- Bootstrap CSS and JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<!-- CSS for Minty Theme, made by Thomas Park on Bootswatch: https://bootswatch.com/minty/ -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<!-- Google Analytics Script: https://developers.google.com/analytics/devguides/collection/analyticsjs -->
    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-XXXXX-Y', 'auto');
        ga('send', 'pageview');
    </script>

conscious_consumer/templates/partials/navbar.html
<!-- conscious_consumer/templates/partials/navbar.html -->
{% load static %}
<nav class="navbar navbar-expand-md navbar-dark bg-primary">
    <!-- Left hand side displays logo and site header -->
    <div class="navbar-brand d-flex w-50 ml-2">
        <span class="text-white">
            <div class="row">
                <img src="{% static 'images/internet.png' %}" width=50px height=50px>
                <h2>
                    <a class="ml-1" href="{% url 'landing_page' %}" style="color: white;">
                        <!-- Site brand label chnages based on authentication -->
                        {% if not user.is_authenticated %}
                            Conscious Consumer
                        {% else %}
                            Hello, {{ user.username }}!
                        {% endif %}
                    </a>
                </h2>
            </div>
        </span>
     </div>
    <!-- smaller button for smaller viewports -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon text-white"><h4></h4></span>
     </button>
    <!-- options for user -->
    <div class="collapse navbar-collapse" id="navbarContent">
         <ul class="list-group list-group-horizontal justify-content-end ml-auto" style="list-style-type: none;">
             <div class="row ml-auto mr-2">
                <li>
                    <a href="{% url 'store:product_list' %}" class="btn btn-primary ml-2">Marketplace</a>
                </li>
                <li>
                    <a href="{% url 'budget:goal_list_public' %}" class="btn btn-primary ml-2">Goals</a>
                </li>
                <li>
                    {% if not user.is_authenticated %}
                    <a href="{% url 'accounts:login' %}" class="btn btn-secondary ml-12">Log In</a>
                    {% else %}
                    <a href="{% url 'accounts:profile_detail' user.profile.id %}" class="btn btn-secondary ml-12">My Account</a>
                    {% endif %}
                </li>
            </div>
        </ul>
    </div>
</nav>