conscious_consumer/api/urls.py
from django.urls import path
from .views import GoalData

app_name = "api"
urlpatterns = [
    # Returns achievement and fail data for a Goal
    path("<int:pk>/chart/data/", GoalData.as_view(), name="goal_data"),
]

conscious_consumer/budget/urls.py
from django.urls import path
from .views import (
    AllGoalList,
    PersonalGoalList,
    PersonalGoalDetail,
    PublicGoalDetail,
    GoalCreate,
    GoalUpdate,
    GoalDelete,
)

app_name = "budget"
urlpatterns = [
    # Goal-related CRUD URLs - id of user is passed to query string on personal
    path("goals/public/", AllGoalList.as_view(), name="goal_list_public"),
    path("goals/create/", GoalCreate.as_view(), name="goal_create"),
    path("goals/update/<slug:slug>/", GoalUpdate.as_view(), name="goal_update"),
    path("goal/delete/<slug:slug>/", GoalDelete.as_view(), name="goal_delete"),
    path("goals/<slug:slug>/", PublicGoalDetail.as_view(), name="goal_detail_public"),
    path(
        "goals/<int:pk>/<slug:slug>/",
        PersonalGoalDetail.as_view(),
        name="goal_detail_personal",
    ),
    path("<int:pk>/", PersonalGoalList.as_view(), name="goal_list_personal"),
]

conscious_consumer/budget/models.py
from django.db import models
from django.conf import settings as dj_conf_settings
import conscious_consumer.settings.settings as cc_settings
from django.utils.text import slugify
from django.urls import reverse


class Goal(models.Model):
    title = models.CharField(
        max_length=cc_settings.LABEL_MAX_LENGTH,
        unique=True,
        help_text="Title of the goal.",
    )
    author = models.ForeignKey(
        dj_conf_settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        null=True,
        help_text="The user that posted this article.",
    )
    slug = models.CharField(
        max_length=cc_settings.LABEL_MAX_LENGTH,
        blank=True,
        editable=False,
        help_text=(
            "Unique URL path to access this goal. " + "Generated by the system."
        ),
    )
    description = models.TextField(help_text="The full details of the goal.")
    created = models.DateTimeField(
        auto_now_add=True,
        help_text=(
            "The date and time this goal was"
            + " created. Automatically "
            + "generated when the model "
            + "saves."
        ),
    )
    modified = models.DateTimeField(
        auto_now=True,
        help_text=(
            "The date and time this goal "
            + "was updated. Automatically "
            + "generated when the model "
            + "updates."
        ),
    )
    achievements = models.PositiveIntegerField(
        help_text=(
            "The number of time periods you have met this goal. "
            + "Start at 0 - honor system!"
        )
    )
    fails = models.PositiveIntegerField(
        help_text=(
            "The number of time periods you have missed this goal. "
            + "Start at 0 - honor system!"
        )
    )
    # user can set a category and must set a value for each of their goals
    HOME_CAT = "Home"
    LIVING_CAT = "Living"
    FOOD_CAT = "Food"
    SHOPPING_CAT = "Shopping"
    TRAVEL_CAT = "Travel"
    CATEGORY_CHOICES = [
        (HOME_CAT, "Home"),
        (LIVING_CAT, "Living"),
        (FOOD_CAT, "Food"),
        (SHOPPING_CAT, "Shopping"),
        (TRAVEL_CAT, "Travel"),
    ]
    category = models.CharField(
        null=True,
        blank=True,
        choices=CATEGORY_CHOICES,
        max_length=8,
        help_text=("What area of life relates to your goal?"),
    )
    MIN_VALUE = 0.03
    LOW_VALUE = 0.06
    MEDIUM_VALUE = 0.09
    HIGH_VALUE = 0.12
    MAX_VALUE = 0.17
    CARBON_CHOICES = [
        (MIN_VALUE, "0.03 tons/mo. - Lower limit"),
        (LOW_VALUE, "0.06 tons/mo. - Almost-there limit"),
        (MEDIUM_VALUE, "0.09 tons/mo. - Reasonable limit"),
        (HIGH_VALUE, "0.12 tons/mo. - Making-progress limit"),
        (MAX_VALUE, "0.17 tons/mo. - Upper limit"),
    ]
    monthly_target = models.FloatField(
        default=MAX_VALUE,
        choices=CARBON_CHOICES,
        help_text=("Tons carbon will you limit " + "yourself to each month."),
    )

    def save(self, *args, **kwargs):
        """Creates a URL safe slug automatically when a new a goal is made."""
        if not self.pk:
            self.slug = slugify(self.title, allow_unicode=True)

        # Call save on the superclass.
        return super(Goal, self).save(*args, **kwargs)

    def __str__(self):
        """Return a descriptive name to reference the goal."""
        return f"{self.title}"

    # Credit for this implementation goes to Dani Roxberry at
    # https://github.com/UPstartDeveloper/makewiki_v2/blob/master/wiki/models.py
    def get_absolute_url_public(self):
        """Returns a path for a goal (uses public page). Follows GoalCreate."""
        path_components = {"slug": self.slug}
        return reverse("budget:goal_detail_public", kwargs=path_components)

    def get_absolute_url_personal(self, id):
        """Returns a path for a goal (uses public page). Follows GoalUpdate."""
        path_components = {"pk": id, "slug": self.slug}
        return reverse("budget:goal_detail_personal", kwargs=path_components)


class Comment(models.Model):
    user = models.OneToOneField(
        dj_conf_settings.AUTH_USER_MODEL,
        on_delete=models.PROTECT,
        help_text="User who wrote the comment.",
    )
    goal = models.ForeignKey(
        Goal, on_delete=models.PROTECT, help_text="Goal referred to by the comment."
    )
    headline = models.CharField(
        max_length=cc_settings.LABEL_MAX_LENGTH,
        editable=True,
        help_text=("Main gist of the comment."),
    )
    description = models.TextField(help_text="Full description of comment.")
    last_modified = models.DateTimeField(
        auto_now_add=True,
        help_text=(
            "The date and time this comment" + " was last edited. Auto-generated."
        ),
    )

    def __str__(self):
        """Return a descriptive name to reference the comment."""
        return f"Comment {self.id} for '{self.goal}'"

conscious_consumer/budget/forms.py
from django import forms
from .models import Goal, Comment


class GoalForm(forms.ModelForm):
    class Meta:
        model = Goal
        exclude = [
            "author",
            "slug",
            "created",
            "modified",
        ]


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            "headline",
            "description",
        ]

conscious_consumer/budget/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Goal
from .forms import GoalForm
from django.urls import reverse, reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User


# Goal CRUD
class AllGoalList(ListView):
    """User sees goal from all users on the site."""

    model = Goal
    template_name = "budget/goal/list-all.html"
    queryset = Goal.objects.all()

    def get(self, request):
        """Render a context containing all Goal instances."""
        goals = self.queryset
        context = {"goals": goals}
        return render(request, self.template_name, context)


class PersonalGoalList(ListView):
    """User sees goals only pertaining to themself."""

    model = Goal
    template_name = "budget/goal/list-personal.html"

    def get(self, request, pk):
        """Render a context containing all Goal specific to the user."""
        user = User.objects.get(id=pk)
        goals = self.get_queryset().filter(author=user)
        return render(request, self.template_name, {"goals": goals})


class PersonalGoalDetail(DetailView):
    """User sees details specific to a single goal which they wrote."""

    model = Goal
    template_name = "budget/goal/detail-personal.html"

    def get(self, request, pk, slug):
        """Renders a page to show the details for a specific Goal.
        If the user is viewing a goal another user wrote, they will see both
        the goal and comments associated with it.
        If the user views a goal they authored, they will be able to see the
        goal, along with some data visualizations of how well they've kept
        on track.

        Parameters:
        request(HttpRequest): the GET request sent to the server
        pk(int): unique id value of the user
        slug(slug): unique slug of the Goal being requested

        Returns:
        HttpResponse: the view of either the personal or public template

        """
        # determine if the request user is the author or not
        user = User.objects.get(id=pk)
        goal = Goal.objects.get(slug__iexact=slug)
        # if they are, display the personal template
        if goal.author == user:
            template = self.template_name
            context = {"goal": goal}
            return render(request, template, context)
        # otherwise display the public template
        else:
            return redirect(goal.get_absolute_url_public())


class PublicGoalDetail(DetailView):
    """User sees details specific to a single goal, written by someone else."""

    model = Goal
    template_name = "budget/goal/detail-public.html"

    def get(self, request, slug):
        """Renders a page to show the details for a specific Goal.

        Parameters:
        request(HttpRequest): the GET request sent to the server
        slug(slug): unique slug of the Goal being requested

        Returns:
        HttpResponse: the view of public template

        """
        goal = Goal.objects.get(slug__iexact=slug)
        context = {"goal": goal}
        return render(request, self.template_name, context)


class GoalCreate(UserPassesTestMixin, CreateView):
    """User submits a form to add a new goal for themself."""

    model = Goal
    form_class = GoalForm
    template_name = "budget/goal/create.html"
    queryset = Goal.objects.all()

    def form_valid(self, form):
        """Initializes the author based on who submitted the form."""
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        """Returns a fully-qualified path to the Goal's personal details."""
        url = self.object.get_absolute_url_public()
        return url

    def test_func(self):
        """Restrict viewing of the form to authenticated users."""
        return self.request.user.is_authenticated is True


class GoalUpdate(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    """User submits a form to edit one of their goal."""

    model = Goal
    form_class = GoalForm
    template_name = "budget/goal/update.html"
    queryset = Goal.objects.all()

    def get_success_url(self):
        """Returns a fully-qualified path to the Goal's personal details."""
        goal = self.get_object()
        id = self.request.user.id
        return goal.get_absolute_url_personal(id)

    def test_func(self):
        """Ensures the user editing the goal is its author."""
        goal = self.get_object()
        return self.request.user == goal.author


class GoalDelete(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """User submits a form to delete one of their goals."""

    model = Goal
    template_name = "budget/goal/delete.html"
    success_url = reverse_lazy("budget:goal_list_public")
    queryset = Goal.objects.all()

    def get(self, request, slug):
        """Renders a short preview of thr goal, along with form to delete.

        Parameters:
        request(HttpRequest): the GET request sent to the server
        slug(slug): unique slug field value of the Goal instance

        Returns:
        HttpResponse: the view of the detail template

        """
        goal = self.get_queryset().get(slug__iexact=slug)
        context = {"goal": goal}
        return render(request, self.template_name, context)

    def test_func(self):
        """Ensures the user removing the goal is its author."""
        goal = self.get_object()
        return self.request.user == goal.author

conscious_consumer/budget/templates/budget/goal/create.html
<!-- conscious_consumer/budget/templates/budget/goal/create.html -->
{% extends "base.html" %}

{% block content %}
    <h1>Set a New Goal</h1>
    <!-- Motivation for User -->
    <h2 class="mt-2"><strong>Challenge yourself!</strong></h2>
    <p>Making a change in your lifestlye habits is never easy. <br>
        Take steps each day to improve, even 0.1% each day is better than nothing. <br>
        If you fail, be kind to yourself - we promise you'll thank yourself in the future for making this effort! 🤩
    </p>
    <!-- Form to Fill Out -->
    <h3>Fill out the Form Below</h3>
        {% include 'partials/form.html' %}
    <br>
    <a class="btn btn-primary" href="{% url 'budget:goal_list_public'%}">See All Goals</a>
    <a class="btn btn-info" href="{% url 'budget:goal_list_public'%}">See Your Goals</a>

{% endblock %}

conscious_consumer/budget/templates/budget/goal/delete.html
<!-- conscious_consumer/budget/templates/budget/goal/delete.html -->
{% extends "base.html" %}

{% block content %}
<h1>Delete Goal</h1>
<!-- Message for User -->
<h2>Wait, <i>what?</i> You're Not Giving Up Are You?</h2>
<p><strong>"Winners don't quit and quitters don't win"</strong> - Vince Lombardi, <i>NFL Coach and 5-time Super Bowl champion</i></p>
<!-- Deletion form -->
<h3>This action <strong>cannot</strong> be undone. Here is what will be deleted:</h3>
{% include 'partials/common-goal-summary.html' %}

<h3>Are you sure you would like to continue?</h3>
<form method="post">
    {% csrf_token %}
    <div class="row">
        <input type="submit" class="btn btn-secondary ml-4 mr-2" value="Confirm">
        {% if user.is_authenticated %}
            <a href="{% url 'budget:goal_detail_personal' user.id goal.slug %}" class="btn btn-success">Back to Goal Page</a>
        {% endif %}
    </div>
</form>

{% endblock %}

conscious_consumer/budget/templates/budget/goal/detail-personal.html
<!-- conscious_consumer/budget/templates/budget/goal/detail-personal.html -->
{% extends "base.html" %}

{% block content %}
<!-- Show Goal Information (and comments if any) -->
{% include 'partials/common-goal-detail.html' %}
<!-- Display Goal Analytics -->
<h3>How to Keep Track of Your Goals</h3>
<ol>
    <li>Pick a check-in date for yourself.</li>
    <li>Every month on that date, go to
        <a href="https://www.nature.org/en-us/get-involved/how-to-help/carbon-footprint-calculator/" target="_blank">
            the carbon calculator on The Natural Conservancy
        </a>.
        <br>
        Judge whether or not you stayed below your carbon budget or not.
    </li>
    <li>Edit your Goal below, updating the numbers of "achievements" and "fails" accordingly. The results will be reflected on this page.</li>
</ol>
<p>
    <strong>Don't cheat!</strong> This page is visible only to you, so if you lie you're only doing yourself (and the planet) a disservice.
</p>
<!-- Links to All Personal Goals, Update, and Delete -->
<div class="row mb-3">
    <a href="{% url 'budget:goal_list_personal' user.id %}" class="btn btn-primary ml-3 mr-3">Back to All Personal Goals</a>
    <a href="{% url 'budget:goal_update' goal.slug %}" class="btn btn-info mr-3">Edit Goal</a>
    <a href="{% url 'budget:goal_delete' goal.slug %}" class="btn btn-secondary">Delete Goal</a>
</div>
<!-- Data Visualizations -->
<div class="container mt-3">
    <div class="row"></div>
    <div class="row">
        <div class="col-md-6">
            <h3>Staying on Budget</h3>
            <p>Observe the pie chart to the right to see how many months you have
            stuck to your carbon budget, and how many you have gone over.</p>
        </div>
        <div class="col-md-6">
            <!-- if there's no data yet, then show no visualization and inform user -->
            {% if goal.achievements == 0 and goal.fails == 0 %}
            <div class="alert alert-danger" role="alert">
                You have not recorded any achievements or failures for this goal.
            </div>
            {% else %}
                <canvas id="doughnutChart" width="200" height="200"></canvas>
                {% include 'partials/doughnut-chart.html' %}
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

conscious_consumer/budget/templates/budget/goal/detail-public.html
<!-- conscious_consumer/budget/templates/budget/goal/detail-public.html -->
{% extends "base.html" %}

{% block content %}
<!-- Show Goal Information (and comments if any) -->
{% include 'partials/common-goal-detail.html' %}
<!-- Link to All Goals -->
<a href="{% url 'budget:goal_list_public' %}" class="btn btn-primary">Back to All Goals</a>
{% endblock %}

conscious_consumer/budget/templates/budget/goal/list-all.html
<!-- conscious_consumer/budget/templates/budget/goal/list-all.html -->
{% extends "base.html" %}

{% block content %}
<h1>All Goals</h1>
<!-- Info Message to User -->
<p>Curious what we're up to? <br>
    Check out all goals Conscious Consumer have set below! <br>
    <!-- Link to other goals page -->
    {% if user.is_authenticated %}
        <a href="{% url 'budget:goal_list_personal' user.id %}">
            To see only your own goals: be sure to log in,
            and then click here!
        </a>
    {% endif %}
</p>
<!-- List of all goals -->
    <!-- Link to Create a Goal -->
    <div class="row mb-3">
        <a href="{% url 'budget:goal_create' %}" class="btn btn-info mr-auto ml-3">Set a New Goal</a>
    </div>
    <div class="card-columns">
        {% for goal in goals %}
            {% include 'partials/common-goal-summary.html' %}
        {% endfor %}
    </div

{% endblock %}

conscious_consumer/budget/templates/budget/goal/list-personal.html
<!-- conscious_consumer/budget/templates/budget/goal/list-personal.html -->
{% extends "base.html" %}

{% block content %}
<h1>Personal Goals</h1>
<!-- Info Message to User -->
<h3>Take a look at your progress!</h3>
<p>Below are all your goals in this system.</p>

<!-- List of all goals -->
    <!-- Link to Create a Goal -->
    <div class="row mb-3">
        <a href="{% url 'budget:goal_create' %}" class="btn btn-info mr-auto ml-3">Set a New Goal</a>
    </div>
<div class="row">
    <div class="col-md-9">
        {% for goal in goals %}
            {% include 'partials/personal-goal-summary.html' %}
        {% endfor %}
    </div>
</div>

{% endblock %}

conscious_consumer/budget/templates/budget/goal/update.html
<!-- conscious_consumer/budget/templates/budget/goal/update.html -->
{% extends "base.html" %}

{% block content %}
<h1>Change a Goal</h1>
<!-- Motivation to User -->
<h3>We encourage change!</h3>
<p>
    <ul>Please modify your goals if you fall in either of the following two scenarios:
        <li>
            You're crushing it so far! And now you feel ready for a greater challenge 👏
        </li>
        <li>
            You've had some issues, and feel this is a good way to step back for a moment before moving on. 👍
        </li>
    </ul>
</p>
<!-- Update Form -->
<h3>Edit your Goal Below</h3>
{% include 'partials/form.html' %}
    {% if user.is_authenticated %}
        <a href="{% url 'budget:goal_detail_personal' user.id goal.slug %}" class="mt-2 btn btn-info">Back to Goal Page</a>
    {% endif %}

<!-- Motivational Quote -->
<div class="row mt-2">
    <p><strong>"Your life does not get better by chance, it gets better by change."</strong> - Jim Rohn, <i>author and motivational speaker</i></p>
</div>

{% endblock %}