conscious_consumer/accounts/urls.py
from django.urls import path
import django.contrib.auth.views as auth_views
from accounts.views import (
    SignupView,
    ProfileDetail,
    ProfileUpdate,
    UserUpdate,
    UserDelete,
    BeginPasswordChange,
    PasswordChangeComplete,
)

app_name = "accounts"
urlpatterns = [
    # auth related views
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="accounts/auth/login.html"),
        name="login",
    ),
    path("signup/", SignupView.as_view(), name="signup"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    # profile related views
    path(
        "<int:pk>/change-profile-image/", ProfileUpdate.as_view(), name="change_image"
    ),
    path(
        "<int:pk>/change-account-info/",
        UserUpdate.as_view(),
        name="change_account_info",
    ),
    path("<int:pk>/delete-account/", UserDelete.as_view(), name="profile_delete"),
    path("<int:pk>/", ProfileDetail.as_view(), name="profile_detail"),
    # password-related views=
    path("password-change/", BeginPasswordChange.as_view(), name="password_change"),
    path(
        "password-change/done/",
        PasswordChangeComplete.as_view(),
        name="password_change_done",
    ),
]

conscious_consumer/api/urls.py
from django.urls import path
from .views import GoalData

app_name = "api"
urlpatterns = [
    # Returns achievement and fail data for a Goal
    path("<int:pk>/chart/data/", GoalData.as_view(), name="goal_data"),
]

conscious_consumer/accounts/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings as dj_conf_settings
import conscious_consumer.settings.settings as cc_settings
from store.models import Product


class Profile(models.Model):
    """Inspiration for the mugshot field, as well as the __str__ and
    get_absolute_url method, goes to Travelly source code:
    https://github.com/UPstartDeveloper/fiercely-souvenir/blob/master/travelly/accounts/models.py

    """

    user = models.OneToOneField(
        dj_conf_settings.AUTH_USER_MODEL, on_delete=models.CASCADE
    )
    mugshot = models.ImageField(
        upload_to="images/",
        default="images/user-icon.jpg",
        help_text="User profile image",
    )

    def __str__(self):
        """Return the related User's username."""
        return f"{self.user.username}'s Profile"

    def get_absolute_url(self):
        """Returns a fully qualified path for user profile."""
        path_components = {"pk": self.id}
        return reverse("accounts:profile_detail", kwargs=path_components)


class Interest(models.Model):
    profile = models.ForeignKey(
        Profile, on_delete=models.CASCADE, help_text="Related user profile."
    )
    label = models.CharField(
        max_length=cc_settings.LABEL_MAX_LENGTH,
        editable=True,
        help_text=(
            "Category of products that would make it easier "
            + "for this user to keep to their buget goals."
        ),
    )
    product = models.ForeignKey(
        Product,
        on_delete=models.PROTECT,
        help_text=("Related products to be recommended."),
    )


class Notification(models.Model):
    profile = models.ForeignKey(
        Profile, on_delete=models.CASCADE, help_text="Related user profile."
    )
    label = models.CharField(
        max_length=cc_settings.LABEL_MAX_LENGTH,
        editable=True,
        help_text=(
            "Message to user about someone reviewing their"
            + " product for sale, delivery of a bought product"
            + ", or a comment on their goal by another user."
        ),
    )
    # ... are more fields needed here? I'm putting this feature on hold for now

conscious_consumer/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile

# credit for subclassing UserCreationForm belongs to
# https://overiq.com/django-1-10/django-creating-users-using-usercreationform/


class SignUpForm(UserCreationForm):
    """A form to register new users."""

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

    def save(self, commit=True):
        """Initializes fields of the new User instance."""
        user = super(SignUpForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]

        if commit is True:
            user.save()

        return user


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ["user"]


class UserChangeForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            "username",
            "email",
        ]

conscious_consumer/accounts/views.py
from django.shortcuts import render
from django.conf import settings as dj_conf_settings
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse, reverse_lazy, resolve
from .models import Profile
from .forms import SignUpForm, ProfileForm, UserChangeForm
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth import views as auth_views
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect


class SignupView(SuccessMessageMixin, CreateView):
    """User is able to signup with a username, email, and password."""

    form_class = SignUpForm
    success_url = reverse_lazy("accounts:login")
    template_name = "accounts/auth/signup.html"
    success_message = "Congratulations! You may now log in."

    def form_valid(self, form):
        """Save the new User, and set up their profile as well."""
        self.object = form.save()
        profile = Profile.objects.create(user=self.object)
        profile.save()
        return super().form_valid(form)


class ProfileDetail(UserPassesTestMixin, DetailView):
    model = Profile
    template_name = "accounts/profile/detail.html"

    def get(self, request, pk):
        """Renders a page to show the details for a specific User and the
        related profile.

        Parameters:
        request(HttpRequest): the GET request sent to the server
        pk(int: unique id of the Profile being requested

        Returns:
        HttpResponse: the view of public template

        """
        profile = self.model.objects.get(id=pk)
        context = {"profile": profile}
        return render(request, self.template_name, context)

    def test_func(self):
        """Ensure that the user is viewing their own profile."""
        profile = self.get_object()
        return profile.user == self.request.user


class ProfileUpdate(UserPassesTestMixin, UpdateView):
    """A user uploads their profile image through a form."""

    model = Profile
    form_class = ProfileForm
    template_name = "accounts/profile/change-picture.html"
    queryset = Profile.objects.all()

    def test_func(self):
        """Ensure that the user is changing their own profile."""
        profile = self.get_object()
        return profile.id == self.request.user.profile.id


class UserUpdate(LoginRequiredMixin, UpdateView):
    """A user changes their username or email."""

    model = User
    form_class = UserChangeForm
    template_name = "accounts/profile/change-user.html"
    queryset = User.objects.all()
    login_url = "accounts:login"

    def get_success_url(self):
        """Redirect to the profile page of the updated User object."""
        url = self.object.profile.get_absolute_url()
        return url


class UserDelete(DeleteView):
    model = User
    template_name = "accounts/profile/delete.html"
    success_url = reverse_lazy("accounts:login")
    queryset = User.objects.all()


class BeginPasswordChange(SuccessMessageMixin, auth_views.PasswordChangeView):
    """A form to enter a new password for the authenticated user."""

    template_name = "accounts/auth/password/change-form.html"
    success_url = reverse_lazy("accounts:password_change_done")
    success_message = "Your password was changed successfully!"


class PasswordChangeComplete(auth_views.PasswordChangeDoneView):
    template_name = "accounts/profile/detail.html"
    success_message = "Your password was changed successfully!"

conscious_consumer/accounts/templates/accounts/profile/change-picture.html
<!-- conscious_consumer/accounts/templates/accounts/profile/change-picture.html -->
{% extends "base.html" %}

{% block content %}
<h1>Upload Profile Image</h1>
<div class="mt-3 mb-2">
    {% include 'partials/form.html' %}
</div>
<a class="btn btn-secondary" href="{% url 'accounts:profile_detail' user.profile.id %}">Back to Profile</a>

{% endblock %}

conscious_consumer/accounts/templates/accounts/profile/change-user.html
<!-- conscious_consumer/accounts/templates/accounts/profile/change-user.html -->
{% extends "base.html" %}

{% block content %}
<h1>Edit Account Information</h1>
<div class="mt-3 mb-2">
    {% include 'partials/form.html' %}
</div>
<a class="btn btn-secondary" href="{% url 'accounts:profile_detail' user.profile.id %}">Back to Profile</a>

{% endblock %}

conscious_consumer/accounts/templates/accounts/profile/delete.html
<!-- conscious_consumer/accounts/templates/accounts/profile/delete.html -->
{% extends "base.html" %}

{% block content %}
<h1>Delete Account</h1>
<!-- Message for User -->
<h2>Wait, <i>what?</i> You're Not Giving Up Are You?</h2>
<p><strong>"Winners don't quit and quitters don't win"</strong> - Vince Lombardi, <i>NFL Coach and 5-time Super Bowl champion</i></p>
<!-- Deletion form -->
<h3>This action <strong>cannot</strong> be undone.


<h3>Are you sure you would like to continue?</h3>
<form method="post">
    {% csrf_token %}
    <div class="row">
        <input type="submit" class="btn btn-secondary ml-4 mr-2" value="Confirm">
        <a href="{% url 'accounts:profile_detail' user.profile.id %}" class="btn btn-success">Back to Profile</a>
    </div>
</form>


{% endblock %}

conscious_consumer/accounts/templates/accounts/profile/detail.html
<!-- conscious_consumer/accounts/templates/accounts/profile/detail.html -->
{% extends "base.html" %}

{% load static %}
{% block content %}
    <!-- if user has just changed password -->
    {% if messages %}
        <div class="messages">
            {% for message in messages %}
            <p{% if message.tags %} class="{{ message.tags }} alert alert-success"{% endif %}>{{ message }}</p>
            {% endfor %}
        </div>
    {% endif %}
    <!-- display account information -->
    <div class="row">
        <div class="col-md-6">
            <!-- Greeting -->
            <h1 class="mb-4">Account Details</h1>
            <!-- User Info -->
            <div class="row">
                <h2 class="ml-3 mr-3">Profile Information:</h2>
            </div>
            <div class="row">
                <ul>
                    <li>Username: {{ user.username }}</li>
                    <li>Email: {{ user.email }}</li>
                </ul>
            </div>
            <!-- Links to Other Pages -->
            <div class="row ml-2">
                <h3>Options</h3>
            </div>
            <div class="row ml-2">
                <div class="col-md-6">
                    <a href="{% url 'accounts:password_change' %}" class="btn btn-info mb-2">Change Password</a>
                </div>
                <div class="col-md-6">
                    <a href="{% url 'accounts:change_account_info' user.id %}" class="btn btn-outline-info mr-5 mb-3">Edit Info</a>
                </div>
            </div>
            <div class="row ml-2">
                <div class="col-md-6">
                    <a href="{% url 'accounts:profile_delete' user.id %}" class="btn btn-danger mb-2">Delete Account</a>
                </div>
                <div class="col-md-6">
                    <a href="{% url 'accounts:logout' %}" class="btn btn-outline-danger">Log Out</a>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <!-- Profile Image -->
            <div class="row justify-content-center">
                <!-- Show the User Profile Image, or the Default Images (works on Env w/o AWS variables -->
                <img class="mb-3" src="{{ profile.mugshot.url }}" alt="Profile image" height=400px width=400px>
            </div>
            <div class="row">
                <div class="col-md-4"></div>
                <div class="col-md-4">
                    <a href="{% url 'accounts:change_image' user.profile.id %}" class="btn btn-outline-secondary mr-2 mb-3">Upload Image</a>
                </div>
                <div class="col-md-4"></div>
            </div>
        </div>
    </div>
{% endblock %}