conscious_consumer/api/urls.py
from django.urls import path
from .views import GoalData

app_name = "api"
urlpatterns = [
    # Returns achievement and fail data for a Goal
    path("<int:pk>/chart/data/", GoalData.as_view(), name="goal_data"),
]

conscious_consumer/store/urls.py
from django.urls import path
from .views import (
    ProductList,
    ProductCreate,
    ProductDetail,
    ProductUpdate,
    ProductDelete,
)

app_name = "store"
urlpatterns = [
    # Product CRUD-related URLs
    path("products/", ProductList.as_view(), name="product_list"),
    path("products/new/", ProductCreate.as_view(), name="product_create"),
    path("products/<slug:slug>/edit/", ProductUpdate.as_view(), name="product_update"),
    path(
        "products/<slug:slug>/delete/", ProductDelete.as_view(), name="product_delete"
    ),
    path("products/<slug:slug>/", ProductDetail.as_view(), name="product_detail"),
]

conscious_consumer/store/models.py
from django.db import models
from django.conf import settings as dj_conf_settings
import conscious_consumer.settings.settings as cc_settings
from django.urls import reverse
from django.utils.text import slugify


class Product(models.Model):
    title = models.CharField(
        max_length=cc_settings.LABEL_MAX_LENGTH,
        unique=True,
        help_text="What the product is called.",
    )
    slug = models.CharField(
        max_length=cc_settings.LABEL_MAX_LENGTH,
        blank=True,
        editable=False,
        help_text=(
            "Unique URL path to access this product. " + "Generated by the system."
        ),
    )
    description = models.TextField(
        help_text=(
            "What customers should know."
            + "Please include the link, if you're selling"
            + " on a different website."
        )
    )
    photo = models.ImageField(
        upload_to="images/",
        null=True,
        blank=True,
        default="images/question-mark-md.png",
        help_text="Image of the product, if possible.",
    )
    price = models.FloatField(help_text="Cost of product (USD).")
    seller = models.ForeignKey(
        dj_conf_settings.AUTH_USER_MODEL,
        on_delete=models.PROTECT,
        help_text="User who posted this product.",
    )
    monthly_emission = models.FloatField(
        null=True,
        blank=True,
        help_text=(
            "Metric tons of carbon emitted monthly by someone using this product"
            + " or service."
        ),
    )
    stock = models.IntegerField(
        default=0,
        help_text=(
            "Number of available units/customers you are able to service "
            + "currently. Default value: 0. You can always come update this later."
        ),
    )
    web_link = models.CharField(
        null=True,
        blank=True,
        max_length=1000,
        unique=False,
        editable=True,
        help_text="Link to access payment page.",
    )

    def __str__(self):
        """Return a string representation of the Product."""
        return f"{self.title}"

    def save(self, *args, **kwargs):
        """Creates a URL safe slug automatically for each new product."""
        if not self.pk:
            self.slug = slugify(self.title, allow_unicode=True)

        # Call save on the superclass.
        return super(Product, self).save(*args, **kwargs)

    # Credit for this implementation goes to Dani Roxberry at
    # https://github.com/UPstartDeveloper/makewiki_v2/blob/master/wiki/models.py
    def get_absolute_url(self):
        """Returns a fully-qualified path for a product."""
        path_components = {"slug": self.slug}
        return reverse("store:product_detail", kwargs=path_components)


class Review(models.Model):
    product = models.ForeignKey(
        Product, on_delete=models.PROTECT, help_text="Product being reviewed."
    )
    headline = models.CharField(
        max_length=cc_settings.LABEL_MAX_LENGTH,
        unique=False,
        help_text="Main point of review.",
    )
    description = models.TextField(help_text="Full thoughts on product.")
    author = models.OneToOneField(
        dj_conf_settings.AUTH_USER_MODEL,
        on_delete=models.PROTECT,
        help_text="User leaving the review.",
    )
    rating = models.IntegerField(help_text=("1 to 5 stars, where 5 is highest rating."))
    modified = models.DateTimeField(
        auto_now=True,
        help_text=(
            "The date and time this product "
            + "was posted. Automatically "
            + "generated when the model updates."
        ),
    )

    def __str__(self):
        """Return a string representation of the Review."""
        return f"{self.headline}"

    def get_absolute_url(self):
        """Returns a fully-qualified path for a product related to review."""
        path_components = {"slug": self.product.slug}
        # return reverse('store:product_detail', kwargs=path_components)

conscious_consumer/store/forms.py
from django import forms
from .models import Product, Review


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = [
            "title",
            "description",
            "photo",
            "price",
            "web_link",
        ]


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        exclude = [
            "author",
            "modified",
        ]

conscious_consumer/store/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Product, Review
from .forms import ProductForm, ReviewForm
from django.urls import reverse, reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User


# Product CRUD
class ProductList(ListView):
    model = Product
    template_name = "store/product/list.html"

    def get(self, request):
        """Shows all products available in the marketplace."""
        products = self.get_queryset().all()
        return render(request, self.template_name, {"products": products})


class ProductCreate(LoginRequiredMixin, CreateView):
    """Submit a form to post new product for display."""

    model = Product
    form_class = ProductForm
    template_name = "store/product/create.html"
    queryset = Product.objects.all()
    login_url = "accounts:login"

    def form_valid(self, form):
        """Initializes the passenger based on who submitted the form."""
        form.instance.seller = self.request.user
        return super().form_valid(form)


class ProductDetail(DetailView):
    model = Product
    template_name = "store/product/detail.html"

    def get(self, request, slug):
        """Renders a page to show the boarding instructions for a specific
        Product.

        Parameters:
        request(HttpRequest): the GET request sent to the server
        slug(str): unique slug value of the Product instance

        Returns:
        HttpResponse: the view of the detail template

        """
        product = self.get_queryset().get(slug__iexact=slug)
        context = {
            "product": product,
        }
        return render(request, self.template_name, context)


class ProductUpdate(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    """Allows user to update a product."""

    model = Product
    form_class = ProductForm
    template_name = "store/product/update.html"
    queryset = Product.objects.all()
    login_url = "accounts:login"

    def test_func(self):
        """Ensures the user editing the product is its seller."""
        product = self.get_object()
        return self.request.user == product.seller


class ProductDelete(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """Allows for removal of Trip instances by User."""

    model = Product
    template_name = "store/product/delete.html"
    success_url = reverse_lazy("store:product_list")
    login_url = "accounts:login"
    queryset = Product.objects.all()

    def test_func(self):
        """Ensures the user removing the product is its seller."""
        product = self.get_object()
        return self.request.user == product.seller

conscious_consumer/store/templates/store/product/create.html
<!-- conscious_consumer/store/templates/store/product/create.html -->
{% extends "base.html" %}

{% block content %}

    <h1>Add New Product</h1>
    <h2>Welcome to Conscious Sellers!</h2>
    <h3>Through our program you can display your green products and services for free on this site.</h3>
    <p>Please fill out the form below. <i>For payments, you must include a link to another website.</i></p>
    <!-- Create Form -->
        {% include 'partials/form.html' %}

{% endblock %}

conscious_consumer/store/templates/store/product/delete.html
<!-- conscious_consumer/store/templates/store/product/delete.html -->
{% extends "base.html" %}

{% block content %}

    <h1>Delete Product</h1>
    <h2>We're sorry to see you go!</h2>
    <p><strong>This action cannot be undone. </strong>Are you sure you would like to continue?</p>
    <!-- Delete Form -->
    <div class="row">
        <form class="ml-3 mr-3" method="post">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger" value="Delete">
        </form>
        <a class="btn btn-info" href="{% url 'store:product_detail' product.slug %}">Back to Product</a>
    </div>

{% endblock %}

conscious_consumer/store/templates/store/product/detail.html
<!-- conscious_consumer/store/templates/store/product/detail.html -->
{% extends "base.html" %}

{% block content %}

    <!-- Title -->
    <div class="row">
        <h1>{{ product.title }}</h1>
        <p class="ml-auto text-muted">Posted by: {{ product.seller }}</p>
    </div>
    <!-- Info -->
    <div class="row">
        <!--Image -->
        <div class="col-md-6">
            <img src="{{ product.photo.url }}" alt="Product image not being displayed.">
            <!-- Message about image -->
            <div class="mt-2">
                <small><i>Image provided by seller, or question mark if not provided.</i></small>
            </div>
        </div>
        <!-- Description -->
        <div class="col-md-6">
            <h2>Description</h2>
            <p>{{ product.description }}</p>
            <!-- Emissions, Price and Stock -->
            <ul>
                Need-to-Know's:
                <li><strong>Avg. Carbon Emissions</strong>: {{ product.monthly_emission }} metric tons per mo.</li>
                <li><strong>Price</strong>: ${{ product.price }}</li>
                <li><strong>Stock</strong>: {{ product.stock }} units available</li>
            </ul>
            <!-- Pay Now (goes to 3rd Party Site for Now) -->
            {% if product.stock > 1 %}
                <a class="btn btn-success" href="#">Buy Now!</a>
            {% else %}
                <p class="btn btn-secondary">Product Not Available</p>
            {% endif %}
        </div>
    </div>
    <br><br>
    <!-- Links to Other Product Pages -->
    <div class="row">
        <!-- Product Update and Delete Forms -->
        <div class="col-md-6">
            {% if product.seller == user %}
                <a class="btn btn-info" href="{% url 'store:product_update' product.slug %}">Edit Product</a>
                <a class="ml-2 btn btn-danger" href="{% url 'store:product_delete' product.slug %}">Delete Product</a>
            {% endif %}
        </div>
        <br><br>
        <!-- Product List and Create Links -->
        <div class="col-md-6">
            <a href="{% url 'store:product_list' %}" class="btn btn-primary">Back to All Products</a>
            <a href="{% url 'store:product_create' %}" class="btn btn-success">Add Product Listing</a>
        </div>
    </div>

{% endblock %}

conscious_consumer/store/templates/store/product/list.html
<!-- conscious_consumer/store/templates/store/product/list.html -->
{% extends "base.html" %}

{% block content %}

    <h1>A New Way to Live</h1>
    <h2>Shop below for new ways to live greener!</h2>
    <!-- Link to Add a Product -->
    <a href="{% url 'store:product_create' %}" class="btn btn-success">Add Product Listing</a>
    <br><br>
    <!-- display all products in store right now -->
    {% if products %}
        <div class="card-columns">
            {% for product in products %}
                {% include 'partials/product-card.html' %}
            {% endfor %}
        </div>
    <!-- Otherwise show an alert there are no products in stock right now -->
    {% else %}
    <div class="alert alert-info" role="alert">
        <p>Looks like inventory is a little light right now - please check back soon!</p>
    </div>
    {% endif %}

{% endblock %}

conscious_consumer/store/templates/store/product/update.html
<!-- conscious_consumer/store/templates/store/product/update.html -->
{% extends "base.html" %}

{% block content %}

    <h1>Update Product</h1>
    <h2>Make a Change in Your Listing</h2>
    <p>Please fill out the form below./p>
    <!-- Update Form -->
        {% include 'partials/form.html' %}
        <br>
        <a class="btn btn-info" href="{% url 'store:product_detail' product.slug %}">Back to Product</a>

{% endblock %}